### ISSUE TITLE
I can not find the paper “EvoFlow: Grammar-guided evolutionary automated workflow composition with domain-specific operators and ensemble diversity”

### ISSUE THREAD

**Issue by xuhao0521** [jrromero/evoflow_awc#1]
I can not find the paper “EvoFlow: Grammar-guided evolutionary automated workflow composition with domain-specific operators and ensemble diversity” in the Google Scholar。

Could you upload the article to Github? Or provide a download address。
Thank you!

**Comment by jrromero** [comment]
Already published. https://doi.org/10.1016/j.asoc.2024.111292
Thank you.
